language: csharp

os:
  - linux

mono:
  - latest

env: 
  - DOTNETPATH=/home/travis/.dotnet LINUX=1 

sudo: false  # use the new container-based Travis infrastructure

install:
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 DOTNET_CLI_TELEMETRY_OPTOUT=1
  - if [ "$LINUX" ]; then sudo apt install libunwind8; fi
  - wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
  - chmod +x /tmp/dotnet-install.sh
  - /tmp/dotnet-install.sh -v 2.1.402
  - /tmp/dotnet-install.sh -v 2.1.5 --shared-runtime
  - export PATH=$DOTNETPATH:$PATH
  - dotnet --info

script:
  - chmod u+x ./build.sh
  - ./build.sh All