# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

image:
  - Visual Studio 2019
  - Ubuntu2004
before_build:
  # Display .NET Core version
  - dotnet --version
build_script:
  - dotnet tool restore
  - dotnet fake build
test: off
version: 2.0.0.{build}
nuget:
  account_feed: false
  project_feed: false
artifacts:
  - path: TickSpec\bin\Release
    name: release
  - path: 'packed_nugets\*.*'
    type: NuGetPackage
    name: nuget
  